### PR TITLE
Extended search

### PR DESCRIPTION
**Pull request by VyrCossont**
Moving development from glitch-soc/mastodon#1502.

### CODE REVIEW

**Comment by VyrCossont** [comment]
@unknownconstant @Jerry-infosecexchange moving development of the extended search patch here. This is WIP and not currently ready for use.

**Comment by andrew-d** [comment]
My apologies for the drive-by comment, but something that I would find super valuable is the ability to enable full-text search for only moderators/admins on an instance. It's something that I would find very helpful to aid in moderating e.g. hate speech on an instance–specifically, for posts from other instances.

I would be fine with a hard-coded allowlist of account IDs for this, since moderators/admins change infrequently.

I'd be happy to contribute to your efforts here, if this is something you'd be open to.

**Comment by VyrCossont** [comment]
@andrew-d That seems like a useful scenario. Instead of a hard-coded list, what about adding a new permission to the roles system?

**Comment by VyrCossont** [comment]
Current status: I'm still trying to work out why not every status known to the server is indexed. It seems like calling `Status.create!` should do it by triggering Chewy to update the index, but that's only done in two places. `Status.insert` would probably bypass this but isn't used anywhere.

~~It's possible that I'm misinterpreting how Chewy's "crutches" are supposed to work; they seem like extra data used to build the `searchable_by` index field, but maybe at least one crutch needs to return something to have the status get indexed at all?~~ (This wasn't the issue.)

Rails is a *lot* y'all. Real Rube Goldberg hours today. Continuing to learn and investigate.

**Comment by andrew-d** [comment]
> @andrew-d That seems like a useful scenario. Instead of a hard-coded list, what about adding a new permission to the roles system?

Yes, I think this is the "right" way to do it, though I will admit that I'm not familiar with how complicated the roles system is, so I'm unsure how much extra work that would be vs. a hard-coded list. I will spend some time this week looking into it!

**Comment by VyrCossont** [comment]
I still don't know why only creating a local status adds it to the ES index, but I did figure out where to explicitly import statuses and accounts coming from AP messages.

I've also found that Mastodon has its own [search CLI tool](https://docs.joinmastodon.org/admin/tootctl/#search-deploy) so we don't need to invoke Chewy directly when updating the index schema. This command *should* be equivalent:

```bash
RAILS_ENV=production bin/tootctl search deploy
```

**Comment by VyrCossont** [comment]
Good news! It's working: my search index is staying up to date with posts visible to me on the federated timeline.

**Comment by VyrCossont** [comment]
Current installation instructions:

- apply all the changes in this PR
- set `SEARCH_SCOPE=public` or  `SEARCH_SCOPE=public_or_unlisted` in your `.env.production`
- `systemctl restart mastodon-web.service mastodon-sidekiq.service` to reload changed code
- `RAILS_ENV=production bin/tootctl search deploy` to update the index schema and reindex all existing statuses (the reindexing part will take several hours; I recommend running this during off-peak hours if you have them)

If you try this, please let me know how it goes.

**Comment by raynormast** [comment]
Is this compatible with vanilla mastodon (4.0.2)?

I saw that there was the PG-search as well, I wanted to try with ES first, although I can always go the PG route if this isn't an easy patch.

**Comment by VyrCossont** [comment]
@raynormast It should work on vanilla as well. AFAIK the only file that's different between vanilla and Glitch is the example config file, which should be easy to patch by hand if the patch doesn't apply cleanly.

**Comment by nanos** [comment]
> If you try this, please let me know how it goes.

Here it goes: I've tried this on my instance running glitch-soc, and it appears to work just fine.

It looks like it takes 5-10 minutes for new posts from the federated timeline to become searchable, which I assume is just because my server is a bit underspecced.

So, thanks for the patch!

**Comment by Jerry-infosecexchange** [comment]
In an earlier version of the patch, there was a way to order the search by ascending and descending date - that was super helpful - is that still possible to do with the new strategy?

**Comment by VyrCossont** [comment]
@nanos Thanks for the success report! Glad to hear it's working for you too.

**Comment by VyrCossont** [comment]
> In an earlier version of the patch, there was a way to order the search by ascending and descending date - that was super helpful - is that still possible to do with the new strategy?

@Jerry-infosecexchange Sure, that's a pretty simple extension. I didn't include it in this patch because the UX was half-baked and used emoji that are annoying to type on not-iPhones, but integrating it into Mastodon's existing advanced search syntax should be doable. Give me a day.

**Comment by Jerry-infosecexchange** [comment]
Thanks -  I think even just changing the default behavior to search descending (newest posts first) would be a huge win

**Comment by VyrCossont** [comment]
One production issue that came up recently is that ES is apparently now on the critical path for the post ingestion, so if ES goes down, post ingestion can back up, manifesting as errors like `Faraday::ConnectionFailed: Connection refused - Connection refused - connect(2) for "localhost" port 9200 (localhost:9200)` from `ActivityPub::ProcessingWorker` jobs on the `ingress` queue.

I'm not sure why it's not using the custom Chewy strategy for Mastodon, which uses Sidekiq queues starting with `chewy:`, which I think would get run on the `default` queue in Mastodon's default Sidekiq config. Maybe that has to be applied explicitly when we do the `import` calls. One more thing to look into.

**Comment by VyrCossont** [comment]
> Thanks - I think even just changing the default behavior to search descending (newest posts first) would be a huge win

@Jerry-infosecexchange Latest commit adds `sort:oldest` and `sort:newest` search operators, and defaults to newest first. You'll need to reindex by running `tootctl search deploy` to add the `created_at` field to the statuses index.

**Comment by VyrCossont** [comment]
Might be useful to replicate some of [Twitter's search operators](https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query#list), especially `is:reply`/`-is:reply`, `has:links`, `has:media`, and maybe `lang:xx`.

**Comment by VyrCossont** [comment]
New operators are working for me. Still need date comparison and especially date range operators.

**Comment by VyrCossont** [comment]
Here are the details on the new operators. All can be inverted by prefixing them with `-`, except for `before:`, `after:`, `scope:`, and `sort:`.

- `domain:mastodon.social`: find only posts from `mastodon.social`. Also works with the instance's own domain, although `is:local` is probably very slightly faster.
- `lang:es`: find posts in Spanish
- `is:`
    - `is:bot`: account that created the post is a bot
    - `is:local`: post is on this instance
    - `is:local_only`: post is a Glitch local-only post
        - ⚠️ admins applying this patch to vanilla Mastodon should remove the line that implements this
    - `is:reply`: post is a reply to another post
    - `is:sensitive`: post is marked as sensitive/🔞
- `has:`
    - `has:cw`: post has a content warning
    - `has:link`: post has at least one link that is not a mention or hashtag, as determined by the parser used to fetch link preview cards
    - `has:media`: post has at least one media attachment
    - `has:poll`: post has a poll attachment
    - `has:tag`: post has at least one hashtag
- `visibility:`: can be `public`, `unlisted`, `private`, `direct`, or `limited`
- `before:`, `after:` with a date:
  - maps to [ES date range search](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-range-query.html) and its behavior may not be what users expect, may need some tuning
  - kind of unclear how to deal with time zones — do Mastodon users have one?
- `scope:classic`: restrict search to current user's bookmarks, favs, boosts, own posts, etc. as in vanilla Mastodon
- `sort:`
    - `sort:newest`: display newest posts first (default)
    - `sort:oldest`: display oldest posts first

Note that with the `sort:newest`, `sort:oldest`, `before:`, and `after:` operators, the `created_at` field they sort or filter on comes from the status, not when we receive it, so you can do things like create posts from [2025](https://social.sitedethib.com/@Claire/109162056592908228) or [4200](https://myfriendsare.gay/notice/APx5K7aeglknMfm1A0), which will then show up at the top of every reverse chrono search result. The easy fix is to clamp `created_at` to the present time the post is indexed. Posts claiming to be from the future may still move forward to the new present time in the event that the post is re-indexed, which can happen either when the index is deployed or when the post is faved, bookmarked, etc. Mastodon doesn't store a `received_at` time for statuses, but arguably, it should.

**Comment by unknownconstant** [comment]
I've only just had the chance to deploy this over glitch and it's clear this is a big step forward.

In terms of scaling, my index rebuild was initially very quick but slowed down a lot half way, towards the end my indexing speed has dropped to under ~250 statuses per second. I expect it's reasonable to assume this as a sustained limit, but I'm unsure where the bottleneck has come from: elastic, postgres, sidekiq etc / worried about lagging on a busy server. (mine is quiet)

From what I've played with though this adds a huge amount of usability to Mastodon. As much as being able to find content I want to see, I've also been able to get a sense of scale for the amount of problematic content that my server comes into contact with.

**Comment by vivlim** [comment]
Is there a filter that restricts the search to the original behavior? Sometimes I really do just want to search that smaller set and getting other results is unnecessarily noisy. 

Also it would be really nice to have the new filters shown somewhere in the ui, though maybe there are too many to pack into the 'advanced search format' popup.

**Comment by VyrCossont** [comment]
> Is there a filter that restricts the search to the original behavior? Sometimes I really do just want to search that smaller set and getting other results is unnecessarily noisy.

@vivlim Should be doable. Let me see if I can do it without too much fuss.

> Also it would be really nice to have the new filters shown somewhere in the ui, though maybe there are too many to pack into the 'advanced search format' popup.

It's probably big enough to fit reminders, if not full docs. That popup also needs to change based on the server's configured search scope, because it'll be wrong if it's set to `public` or `public_or_unlisted`. Unfortunately, I don't really know how to do UI stuff in this stack yet, but I'll happily accept a patch from someone who does.

**Comment by VyrCossont** [comment]
@vivlim Give the `scope:classic` operator in the latest patch a try. No need to reindex, it uses the existing `searchable_by` field.

**Comment by vivlim** [comment]
Thanks, it seems to be working well! 👍

**Comment by sl1txdvd** [comment]
Thanks a lot for sharing this. I tried it on Mastodon 4.1.0-rc1 and I got a lot of errors during indexing

> Error while importing StatusesIndex: undefined local variable or method 'local_only'

**Comment by Jerry-infosecexchange** [comment]
> 

How did you apply this to 4.1.0-rc1?  I have much to learn about GitHub repos and building patches

**Comment by VyrCossont** [comment]
> Thanks a lot for sharing this. I tried it on Mastodon 4.1.0-rc1 and I got a lot of errors during indexing
> 
> 
> 
> > Error while importing StatusesIndex: undefined local variable or method 'local_only'

@sl1txdvd sounds like you're not using Glitch. Local-only posts are a Glitch feature and this patch is based on Glitch. To apply it to vanilla Mastodon, remove lines that reference `local_only` before applying the patch. Try that and let me know how it goes.

> ⚠️ admins applying this patch to vanilla Mastodon should remove the line that implements this

I did document this above, but it's easy to miss.

**Comment by sl1txdvd** [comment]
> How did you apply this to 4.1.0-rc1? I have much to learn about GitHub repos and building patches

I cherry-picked the relevant commits and merged them into standard mastodon

> @sl1txdvd sounds like you're not using Glitch. Local-only posts are a Glitch feature and this patch is based on Glitch. To apply it to vanilla Mastodon, remove lines that reference `local_only` before applying the patch. Try that and let me know how it goes.

Yes I missed the warning, thanks. I'll give it a try.

**Comment by sl1txdvd** [comment]
Works for me. Thanks for sharing. I put the adjusted version for standard mastodon on codeberg. Not promising to rebase it forever, but for the time being, it's here:
https://codeberg.org/rauschen/mastodon/src/branch/search-all-visible-toots

**Comment by rallias** [comment]
@Jerry-infosecexchange I added .patch to the pull request URL, and then did `git am 2.patch` on that patch.

**Comment by supernovae** [comment]
I just squeezed this into mastodon 4.1.0 and i'm running index rebuild right now - will report back. thank you so much for this!!!

**Comment by SouthFox-D** [comment]
Thanks, this feature is very helpful！ 🚀

**Comment by supernovae** [comment]
Running great over on https://universeodon.com - give it a try.  I put some of the operators in the advanced search dropdown to help users.

One feature that i think could wrap it all up is to have search for people such as a people operator that is conditional on the person having this feature enabled:

image

I think people are an activity pub - i didn't go look at code yet (been a crazy few days) but this could be brilliant for helping people be discovered and it would allow them to use hashtags/topics in their bio/profile page and be discoverable with their permission.

also wrote a blog here:  https://blog.universeodon.com/mastodon-advanced-search-is-here

The usability of this search improvement is off the charts! thank you so much!!

**Comment by nanos** [comment]
> I put some of the operators in the advanced search dropdown to help users.

Do you mind sharing the patch for that somewhere? I’d love to do this myself.

**Comment by VyrCossont** [comment]
> > I put some of the operators in the advanced search dropdown to help users.
> 
> Do you mind sharing the patch for that somewhere? I’d love to do this myself.

@supernovae I'd absolutely upstream it here. Only reason I didn't get to it is unfamiliarity with the Mastodon frontend stack.

**Comment by VyrCossont** [comment]
> also wrote a blog here: https://blog.universeodon.com/mastodon-advanced-search-is-here
> 
> The usability of this search improvement is off the charts! thank you so much!!

Thank me by adding a link in that article to this PR! I'll get to rebasing it on 4.1.0 now that it's out.

Opt-in people search sounds workable; I'm not sure if that discovery flag federates, however. Will look into it.

**Comment by andrew-d** [comment]
> > also wrote a blog here: https://blog.universeodon.com/mastodon-advanced-search-is-here
> > The usability of this search improvement is off the charts! thank you so much!!
> 
> Thank me by adding a link in that article to this PR! I'll get to rebasing it on 4.1.0 now that it's out.
> 
> Opt-in people search sounds workable; I'm not sure if that discovery flag federates, however. Will look into it.

I'm pretty sure it does; that setting shows up as the `discoverable` attribute on an `Account`:
```
$ curl -fsSL -H 'Accept: application/activity+json, application/json;q=0.9' 'https://ottawa.place/users/andrew' | jq .discoverable
false
$ curl -fsSL -H 'Accept: application/activity+json, application/json;q=0.9' 'https://ottawa.place/users/leigh' | jq .discoverable
true
```

**Comment by VyrCossont** [comment]
Oh good, that property being federated saves an incredible amount of time and fuss. Looks like it's documented here too: https://docs.joinmastodon.org/spec/activitypub/#discoverable

Weird that `discoverable` federates and the search engine opt-out flag doesn't, but hey, this means we can add a "toot is public and user has the discoverable flag set" search scope for instances that want to be more conservative in their search coverage.

**Comment by supernovae** [comment]
> > also wrote a blog here: https://blog.universeodon.com/mastodon-advanced-search-is-here
> > The usability of this search improvement is off the charts! thank you so much!!
> 
> Thank me by adding a link in that article to this PR! I'll get to rebasing it on 4.1.0 now that it's out.
> 
> Opt-in people search sounds workable; I'm not sure if that discovery flag federates, however. Will look into it.

Done! :) added you on the top and bottom of blog (i meant to DM to ask if you wanted me to share)

I've had people ask for other operators that they would like such as being able to search for particulars of their own content like the old search such as:

bookmarks:  favorites:  :boosts :posts for searching their own saved bookmarks, favorites, boosts, posts

**Comment by supernovae** [comment]
> Oh good, that property being federated saves an incredible amount of time and fuss. Looks like it's documented here too: https://docs.joinmastodon.org/spec/activitypub/#discoverable
> 
> Weird that `discoverable` federates and the search engine opt-out flag doesn't, but hey, this means we can add a "toot is public and user has the discoverable flag set" search scope for instances that want to be more conservative in their search coverage.

That's awesome to hear that the discoverable is federated - that can really help fix finding people with this searchable if users opt in.  I'd love to not have to send people to twitter to find folks when they could just be found by links already in their profile if they selected to be discoverable.

happy to sponsor these features if that would help!

**Comment by nanos** [comment]
One thing that I'd really love to be able to do is search by URL.

E.g. I'd love to be able to search posts linking to `https://www.tbray.org/ongoing/When/202x/2022/12/30/Mastodon-Privacy-and-Search` just to get an idea, of who's posted it before, and what discussions ensued.

But I can't paste in a full URL into the search bar: Searching for `https://www.tbray.org/ongoing/When/202x/2022/12/30/Mastodon-Privacy-and-Search` and `"https://www.tbray.org/ongoing/When/202x/2022/12/30/Mastodon-Privacy-and-Search"` both returns 0 results.

Searching for `"Mastodon-Privacy-and-Search"` on the other hand returns plenty of results.

Just curious as to why that is, and if anything could be done to fix this?

**Comment by VyrCossont** [comment]
Not sure! The URL thing is a known issue mastodon/mastodon#21619 but I'm surprised that quoting it doesn't search for the URL as literal text, instead of the default behavior with URLs, which is to do a WebFinger lookup.

Maybe the ES tokenizer needs to be adjusted, but I think it already uses `uax_url_email` and should treat URLs as a single token.

Another possibility is that it's caused by the special cases of the search service mentioned in mastodon/mastodon#18791 where advanced search behavior is skipped if certain characters aren't present.

Searching for a given URL is a super common use case. I might have some time next week to look into that, and a few of the other requests above.

**Comment by VyrCossont** [comment]
> I've had people ask for other operators that they would like such as being able to search for particulars of their own content like the old search such as:
> 
> 
> 
> bookmarks:  favorites:  :boosts :posts for searching their own saved bookmarks, favorites, boosts, posts 

@supernovae A lot of these sound useful and universally applicable, but I'm not sure how much work will be involved; boosts in particular may need a secondary index. If you have a wish list, I can look into what it might take to implement each item.

However, searching your own posts is an easy one: `from:yourusername searchterm`. I use it *constantly* to make sure I haven't posted the same joke or project update twice. That one should work even on unpatched vanilla Mastodon.

**Comment by nanos** [comment]
Thank you @VyrCossont that is super helpful! I hadn't considered that it's meant to to d a webfinger lookup for URLs. Obviously searching for the URL sans the `https://` prefix works fine (though it does unfortunately need to be quoted), so that's good.

**Comment by supernovae** [comment]
yeah, I agree that that even with classic, we have the old stuff covered fairly well.

The one thing that i'd love to see is the people/profile search if their discovery is enabled. I think that is critical to success of mastodon in general.  Not sure how much effort it is, but if i can throw a bounty up to get PRs out for people to try, count me in.

**Comment by VyrCossont** [comment]
Development of search features continues in #5, which is a superset of this PR that adds full-text account search and improved hashtag search for posts. Thanks to everybody who's helped with or installed these patches!

**Comment by nanos** [comment]
Hi @VyrCossont .

I've applied this PR quite some time ago. Today, I tried to upgrade my glitch-soc instance to 4.1.1, but got a lot of merge conflicts.

Do you have any advice?

**Comment by VyrCossont** [comment]
@nanos Unless you have heavy other customizations, I recommend reverting to base Glitch 4.1.1 and then upgrading to #5, which is a superset of this patch but based on Glitch 4.1.0. Hopefully that will have fewer conflicts.

Some of these features will be mainlined eventually: watch PR mastodon/mastodon#24055 for advanced search operators, and mastodon/mastodon#21627 as the umbrella bug for expanded search scope.

**Comment by nanos** [comment]
Thanks @VyrCossont . I'll look into that!

**Comment by nanos** [comment]
OK, so, just FYI, and/or in case anyone else runs across this:

Reverting the patches, and then applying #5 caused even more merge conflicts. Probably because git wasn't sure which of those reversion I wanted to keep, because applying #5 clearly re-applied a lot of stuff that had previously been reverted. The result was an absolute mess.

Here is what I ended up doing:

1) I merged glitch-soc:main into my branch, using just git, as opposed to GitHub PR. For whatever unknown reason this was much easier, and only resulted in a two minor conflicts, that had nothing to do with this PR.
2) Then merged #5, on top of the changes from this PR already present. This introduced a further very simple conflict (mostly around code style changes).

(should note that I first tried this the other way around, i.e. merge #5 before merging glitch-soc:main, and that was an almighty, unresolvable mess - 0/10 would not recommend ...)

That seems to have worked now 🤞 

> Some of these features will be mainlined eventually

whilst exciting, I'm not looking forward to those merge conflicts 🙈 😆

**Pull request closed without merging**
